config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'main#index'
  get 'main/index'
  get 'main/show'
  get 'main/clients'
  get 'main/contacts'
  get 'orders', to: 'main#orders'
  get 'profile/:id', to: 'main#influencer_profile'
  get 'company/:id', to: 'main#company_profile'
  get 'main/add_cards'
  get 'main/add_clients'
  get 'main/sort_order'
  get 'main/add_orders'
  get 'main/search'
  get 'main/platform_card'
  get 'main/curators'
  post 'main/create_new'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/advertesiment_kind.rb
class AdvertesimentKind < ApplicationRecord
	belongs_to :platform
	has_many :orders, dependent: :destroy
	has_many :prices, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
	belongs_to :staff
	has_many :orders, dependent: :destroy
end

app/models/influencer.rb
class Influencer < ApplicationRecord
	has_many :tags, dependent: :destroy
	has_many :prices, dependent: :destroy
	has_many :subscribers, dependent: :destroy
	validates_format_of :mail, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
	validates :city,  length: { maximum: 30 }
	validates :nick,  length: { maximum: 30 }
	has_and_belongs_to_many :orders
	has_many :influencers_orders, dependent: :destroy
end

app/models/influencers_order.rb
class InfluencersOrder < ApplicationRecord
	belongs_to :order
	belongs_to :influencer
end

app/models/order.rb
class Order < ApplicationRecord
	has_and_belongs_to_many :influencers
	belongs_to :staff
	belongs_to :company
	belongs_to :advertesiment_kind
    has_many :influencers_orders, dependent: :destroy
end

app/models/platform.rb
class Platform < ApplicationRecord
	has_many :subscribers, dependent: :destroy
	has_many :advertesiment_kind, dependent: :destroy
end

app/models/price.rb
class Price < ApplicationRecord
	belongs_to :influencer
	belongs_to :advertesiment_kind
end

app/models/staff.rb
class Staff < ApplicationRecord
	validates_format_of :mail, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
	has_many :companys
	has_many :orders
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
	belongs_to :platform
	belongs_to :influencer
end

app/models/tag.rb
class Tag < ApplicationRecord
	 belongs_to :influencer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  @@current = 0
  @@key = true
  @@number_orders = 20
  @@value = ""
  @@tag = ""

  def self.current()
    @@current
  end

  def self.influencers()
    @@influencers
  end

  def index
  end

  def show
    @influencers = Influencer.take(30)
    @@current = 0
  end

  def clients
    @clients = Company.take(30)
    @@current = 0
  end

  def influencer_profile
    id = params[:id].to_i
    if id.to_s =~ /\A[0-9]+\Z/
      if (@influencer = Influencer.find_by_id(id))
      else
        render :error
      end
    else
      render :error
    end
  end

  def contacts
  end

  def company_profile
    id = params[:id].to_i
    if id.to_s =~ /\A[0-9]+\Z/
      if (@client = Company.find_by_id(id))
         @curator = Staff.find_by_id(@client.staff.id)
      else
        render :error
      end
    else
      render :error
    end
  end
  
  def orders
    @@number_orders = 20
    @@key = true
    @orders = Order.order(:date_order).reverse.take(20)
  end

  def add_cards
    @@current = @@current + 30
    @influencers = Influencer.limit(30).offset(@@current)
    respond_to do |format|
      format.js
    end
  end

  def add_clients
    @@current = @@current + 30
    @clients = Company.limit(30).offset(@@current)
    respond_to do |format|
      format.js
    end
  end

  def add_orders
    @@number_orders = @@number_orders + 20
    if @@key
      @orders = Order.order(:date_order).reverse_order.offset(@@number_orders).limit(20)
    else
      @orders = Order.order(:date_order).limit(20).offset(@@number_orders)
    end
    respond_to do |format|
      format.js
    end
  end

  def sort_order
    if @@key
      @@key = false
      @orders = Order.order(:date_order).take(@@number_orders)
    else
      @@key = true
      @orders = Order.order(:date_order).reverse.take(@@number_orders)
    end
    respond_to do |format|
      format.js
    end
  end

  def search
    @influencers = []
    @nick = params[:nick]
    if @nick.strip.split.size > 1
      for_search_first = @nick.strip.split[0].strip 
      for_search_second = @nick.strip.split[1].strip
      @influencers += Influencer.where('("name" = ? and "surname" ilike ?) or ("surname" = ? and "name" ilike ?)', for_search_first, '%'+ for_search_second + '%', for_search_first, '%' + for_search_second + '%').all
    else
      for_search = '%' + @nick.strip + '%'
      @influencers += Influencer.where('("nick" ilike ?) or ("name" ilike ?) or ("surname" ilike ?)', for_search, for_search, for_search).all
    end
    respond_to do |format|
      format.json do
        render json:
                   { influencers: @influencers}
      end
    end
  end

  def platform_card
    @sort = params[:sort]
    @value = params[:platform_id]
    @tag = params[:tag_id]
    @influencers = []

    if (@sort == "0")
      @value = params[:platform_id]
      @tag = params[:tag_id]
      @@value = @value
      @@tag = @tag
      if (@value != "" and @tag == "")
        Subscriber.where(' "platform_id" = ? and "main" = ? ', @value, "true").order("number_of_subscribers DESC").take(100).map {|cur| @influencers << Influencer.find_by_id(cur.influencer_id)}
      elsif (@value == "" and @tag != "")
        @tag = Tag.find_by_id(@tag).tag
        Tag.where(' "tag" = ? ', @tag).take(100).map {|cur| @influencers << Influencer.find_by_id(cur.influencer_id)}
      else
        ar_s = []
        Subscriber.where(' "platform_id" = ? and "main" = ? ', @value, "true").order("number_of_subscribers DESC").take(500).map {|cur| ar_s << Influencer.find_by_id(cur.influencer_id)}
        @tag = Tag.find_by_id(@tag).tag
        ar_s.map do |el|
          key = 0
          Tag.where(' "influencer_id" = ? ', el.id).map do |el2|
            if (el2.tag == @tag)
              key = 1
            end
          end
          if (key == 1)
            @influencers << el
          end
        end
      end
    else
      if (@@value != "" and @@tag == "")
        Subscriber.where(' "platform_id" = ? and "main" = ? ', @@value, "true").order("number_of_subscribers").take(100).map {|cur| @influencers << Influencer.find_by_id(cur.influencer_id)}
      elsif (@@value == "" and @@tag != "")
        @@tag = Tag.find_by_id(@@tag).tag
        Tag.where(' "tag" = ? ', @@tag).take(100).map {|cur| @influencers << Influencer.find_by_id(cur.influencer_id)}
      else
        ar_s = []
        Subscriber.where(' "platform_id" = ? and "main" = ? ', @@value, "true").order("number_of_subscribers").take(500).map {|cur| ar_s << Influencer.find_by_id(cur.influencer_id)}
        @@tag = Tag.find_by_id(@@tag).tag
        ar_s.map do |el|
          key = 0
          Tag.where(' "influencer_id" = ? ', el.id).map do |el2|
            if (el2.tag == @@tag)
              key = 1
            end
          end
          if (key == 1)
            @influencers << el
          end
        end
      end
    end
    respond_to do |format|
      format.js
    end
  end

  def curators
    @curators = Staff.order(number_of_orders: :desc, work_experience: :desc).limit(20)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aquamarine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://vk.com/js/api/openapi.js?168" type="text/javascript"></script>
    <link rel="shortcut icon" href="../../assets/волна.png" >

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-light bg-light" id="nav">
   
    <a class="navbar-brand" href="<%=root_path%>" id="nav_name">
      <img src="../../assets/волна.png" width="100" height="50">
      AQUAMARINE
    </a>

  <div id="cite_but">
      <a href="<%=main_clients_path%>" class="closing-button"><span>Клиенты</span></a>
      <a href="<%=main_show_path%>" class="closing-button"><span>Инфлюенсеры</span></a>
      <a href="<%=orders_path%>" class="closing-button"><span>Кейсы</span></a>
      <a href="<%=main_curators_path%>" class="closing-button"><span>Сотрудники</span></a>
      <a href="<%=main_contacts_path%>" class="closing-button"><span>Контакты</span></a>
   <div>
  </nav>

    <%= yield %>

  <footer id="foot" class="bg-light text-center text-lg-start">
    <div class="container p-4">
          <span class="contacts"> gendina.nina@mail.ru </span>
          <span class="contacts cont_rgh"> +7 (985) 271-44-07  </span>
          <span class="contacts cont_rgh"> 2-я Бауманская ул., 5  </span>
    </div>
    <div class="text-center p-3" >
      © 2020 Copyright:
      <a class="text-dark" href="https://vk.com/ninel_l">NINEL.com</a>
    </div>
  </footer>

  </body>
</html>

app/views/main/add_cards.js.erb
html = "";
html += "<div class=\"all_cards\">";
<% @influencers.each do |influencer| %>
html += "<a href=\"../../profile/<%= influencer.id %>\"><div class=\"card\">";
html += "<img src= '<%= influencer.avatar %>' class='avatar' width=\"270\" height=\"270\"><div class=\"nick\"><span ><%= influencer.nick.upcase %> </span></div>";
html += "<div><% influencer.subscribers.each do |subscriber|%><% if subscriber.main%><img class='icon' src=\"../<%= subscriber.platform.icon%> \" width=\"40\" height=\"40\"><span class=\"main_count\"><%= subscriber.number_of_subscribers%> +</span></br></br><%else%>";
html +="<img class='icon' src=\"../<%= subscriber.platform.icon%> \" width=\"40\" height=\"40\"><span class=\"count\"><%= subscriber.number_of_subscribers.to_i / 1000%> thou.</span><%end%><%end%></div></div></a>";
<% end %>
html += '</div>';

div = document.createElement('div');
div.innerHTML = html;
target = document.querySelector('#link');
tar = document.querySelector('#lol');
tar.appendChild(div);
target.remove();
ta = document.querySelector('#lil');
ta.appendChild(target);

app/views/main/add_clients.js.erb
html = "";
html += "<div class=\"all_cards\">";
<% @clients.each do |client| %>
html += "<a href=\"../../company/<%= client.id %>\"><div class=\"card_client\"><span class=\"name_client\" ><%= client.name.upcase %> </span><img title=\"Познакомиться поближе с <%= client.name.upcase %> \" src= '<%= client.avatar %>' class='avatar_client' width=\"500\" height=\"250\"></div></a>";
<% end %>
html += '</div>';

div = document.createElement('div');
div.innerHTML = html;
target = document.querySelector('#link');
tar = document.querySelector('#lol');
tar.appendChild(div);
target.remove();
ta = document.querySelector('#lil');
ta.appendChild(target);

app/views/main/add_orders.js.erb
html = "";
html += "<div class=\"all_cards_o\">";
<% @orders.each do |order| %>
	html += "<div class=\"card_order\" onclick=\"addCard(this)\" data-toggle=\"modal\" data-target=\"#exampleModal\"><div class=\"order_name\"><%= order.product%></div><div class=\"order_type\">(<%= order.type_product%>)</div>";
	html += "<div class=\"order_type\"><%= order.advertesiment_kind.kinds%> in <%= order.advertesiment_kind.platform.type_of_activity%> of <img id=\"ic\" src=\"<%= order.advertesiment_kind.platform.icon%> \" height=\"35px\"></div><div class=\"order_curator\" ><span class=\"for\">Curator: </span><%= order.staff.name%> <%= order.staff.surname%></div>";
	html += "<div class=\"for order_curator mar\">Participants: </div>";
	<%total = 0%>
	<% order.influencers.each do |influencer|%>
	html += "<div id=\"inf_nick\" class=\"marg\">@<%= influencer.nick%></div>";
    <%total += Price.find_by_influencer_id_and_advertesiment_kind_id(influencer.id, order.advertesiment_kind_id).price%>
    <%end%>
    <%total_str=""%>
    <% total_str = (total / 1000000).to_s if (total / 1000000) != 0%>
    <%total_str += " "%>
    <% total_str += ((total - (total / 1000000)*1000000) / 1000).to_s%>
    <% total_str += "00" if ((total - (total / 1000000)*1000000) / 1000) == 0%>
    <%total_str += " "%>
    <% total_str += "000"%>
    html += "<div class=\"order_curator \" ><span class=\"for\">Total cost: </span><%= total_str%> rub.</div><div class=\"order_curator\" ><span class=\"for\">Date: </span> <%= order.date_order%></div>";
    html += "<div class=\"order_type\">for  <img id=\"avat_comp\" src=\"<%= order.company.avatar%> \" height=\"30px\" width=\"80\"></div></div>";
<%end%>

html += "</div>"
div = document.createElement('div');
div.innerHTML = html;
target = document.querySelector('#link');
tar = document.querySelector('#lol');
tar.appendChild(div);
target.remove();
ta = document.querySelector('#lil');
ta.appendChild(target);

app/views/main/clients.html.erb
<div id="our_clients">Наши клиенты</div>
<div class="all_card">
	<% @clients.each do |client| %>
	<a href="../../company/<%= client.id %>">
		<div class="card_client">
			<span class="name_client" ><%= client.name.upcase %> </span>
			<img title="Познакомиться поближе с <%= client.name.upcase %> " src= '<%= client.avatar %>' class='avatar_client' width="500" height="250">
		</div>
	</a>
	<% end %>
</div>
<%= link_to  image_tag(image_path('стрелка.png'), class: "mini"), main_add_clients_path(), remote: true, id: "link" , title: 'Загрузить еще компаний'%>
<div id="lil">
	<div id="lol"></div>
</div>

app/views/main/company_profile.html.erb
<div id="client_page">
	<div id="client_prof">
		<div id="client_name"><%= @client.name%></div>
		<hr>
		<div>
			<img id="client_avatar" src="<%= @client.avatar%>" width="800" >
		</div>
		<hr>
		<div id="about_company_tit">About company:</div>
		<div id="about_company">
			Industry: <%= @client.industry%><br>
			We cooperate since <%= @client.start_of_cooperation%><br>
			<%= @client.successful_orders%> successful orders completed<br>
			Curator: <a data-toggle="modal" data-target="#exampleModal" class="to_comp_t"> <%= @client.staff.name%> <%= @client.staff.surname%></a>
			
		</div>
	</div>
	<span id="order" style="padding-left: 95px;">Рекламные заказы:</span>
	<div class="horizontal-scroll-wrapper-c squares-c par client_scroll">
		<% @client.orders.each do |order|%>
		<div>
			<div id="product"><%= order.product%> </div>
			<div id="type_product">(<%= order.type_product%>)</div>
			<div id="platf_kind">
				<%= order.advertesiment_kind.kinds%> in <%= order.advertesiment_kind.platform.name%>
			</div>
			
			<div class="coorator">Influencers:</div>
			<% order.influencers.each do |influencer|%>
			<a href="../../profile/<%= influencer.id %>" id="to_comp">  <div id="inf_nick">@<%= influencer.nick%></div> </a>
			<%end%>
			<div class="coorator">Curator:</div> <span class="to_comp"  >  <%= order.staff.name%> </span>
		</div>
		<%end%>
	</div>
</div>
<div class="modal fade sizet cent" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog sizet" role="document">
		<div class="modal-content sizet color">
			<div class="modal-header sizet color2">
				<h5 class="modal-title sizet" id="exampleModalLabel">Curator</h5>
				<a   class="krest" data-dismiss="modal" aria-label="Close" >
					<img src="../assets/крест.png" width="40" >
				</a>
			</div>
			<div id="tuda" class="modal-body" >
				<div class="card_staff" style="background:url('../assets/узор.png'); height: 3000px;">
					<img src="<%=@curator.avatar%>" class="big" >
					<div class="curator_inf">
						<div id="cur_name"><%=@curator.name%> <%=@curator.surname%></div>
						Position: <%=@curator.position%><br>
						Work experience: <%=@curator.work_experience%><br>
						Number of orders: <%=@curator.number_of_orders%><br>
						Mail: <%=@curator.mail%><br>
					</div>
				</div>
			</div>
			
		</div>
	</div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</div>

app/views/main/orders.html.erb
<div id="title_sort_block">
	<span id="title_sort">Отсортировать по дате </span>
	<span id="help"><%= link_to  image_tag(image_path('https://static.tildacdn.com/tild3235-6338-4830-a134-393966613234/chevron-vector-style.png'), class: "arlow", id: "arlow"), main_sort_order_path(), remote: true, id: "link2"%></span>
</div>
<div class="all_cards_o first">
	<% @orders.each do |order| %>
	
	<div class="card_order" onclick="addCard(this)" data-toggle="modal" data-target="#exampleModal">
		<div class="order_name"><%= order.product%></div>
		<div class="order_type">(<%= order.type_product%>)</div>
		
		<div class="order_type"><%= order.advertesiment_kind.kinds%> in <%= order.advertesiment_kind.platform.type_of_activity%> of <img id="ic" src="../<%= order.advertesiment_kind.platform.icon%> " height="35px"></div>
		
		<div class="order_curator" ><span class="for">Curator: </span><%= order.staff.name%> <%= order.staff.surname%></div>
		<div class="for order_curator mar">Participants: </div>
		<%total = 0%>
		<% order.influencers.each do |influencer|%>
		<div id="inf_nick" class="marg">@<%= influencer.nick%></div>
		<%total += Price.find_by_influencer_id_and_advertesiment_kind_id(influencer.id, order.advertesiment_kind_id).price%>
		<%end%>
		<%total_str=""%>
		<% total_str = (total / 1000000).to_s if (total / 1000000) != 0%>
		<%total_str += " "%>
		<% total_str += ((total - (total / 1000000)*1000000) / 1000).to_s%>
		<% total_str += "00" if ((total - (total / 1000000)*1000000) / 1000) == 0%>
		<%total_str += " "%>
		<% total_str += "000"%>
		<div class="order_curator " ><span class="for">Total cost: </span><%= total_str%> rub.</div>
		<div class="order_curator" ><span class="for">Date: </span> <%= order.date_order%></div>
		
		<div class="order_type">for  <img id="avat_comp" src="<%= order.company.avatar%> " height="30px" width="80"></div>
	</div>
	<%end%>
</div>
<div class="modal fade sizet cent" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog sizet" role="document">
		<div class="modal-content sizet color">
			<div class="modal-header sizet color2">
				<h5 class="modal-title sizet" id="exampleModalLabel">Order</h5>
				<a   class="krest" data-dismiss="modal" aria-label="Close" >
					<img src="assets/крест.png" width="40" >
				</a>
			</div>
			<div id="tuda" class="modal-body">
				
			</div>
			
		</div>
	</div>
</div>

<%= link_to  image_tag(image_path('стрелка.png'), class: "mini"), main_add_orders_path(), remote: true, id: "link" , title: 'Загрузить еще заказов'%>
<div id="lil">
	<div id="lol"></div>
</div>


  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

  <script type="text/javascript">
  	
  	function addCard(element) {
  		target = document.querySelector('#tuda');
  		target.innerHTML = ''
  		target.appendChild(element.cloneNode(true));
  		return
  	}
  	
  </script>

app/views/main/show.html.erb
<div class="input-wrapper" data-text="">
  
  <input id="search"  type="text" placeholder="Search…" data-remote="true" name="nick_search">
</div>
<div  class="ord_form">
  <%= form_with url: "../main/platform_card", method: :get do |form| %>
  <%= form.collection_select :platform_id, Platform.order(:name).uniq { |el| el.name}, :id, :name, :include_blank => "Выберите платформу", :class => "select_send_ajax selectpicker", :id => "collect_platform" %>
  <%arr = []%>
  <% for i in Tag.order(:tag).uniq { |el| el.tag} do%>
  <% i.tag.capitalize!%>
  <% arr << i%>
  <% end %>
  <%= form.hidden_field :sort, value: "0" %>
  <%= form.collection_select :tag_id, arr , :id, :tag , :include_blank => "Выберите направление", :class => "select_send_ajax selectpicker", :id => "collect_tag"%>
  <%= link_to  image_tag(image_path('https://static.tildacdn.com/tild3235-6338-4830-a134-393966613234/chevron-vector-style.png'), class: "ord_img"), main_platform_card_path(params: { sort:"1" }), remote: true, id: "ord" , title: 'Отсортировать по подписчикам'%>
  <%= link_to  "all", main_show_path(), id: "all" , title: 'Отменить опциии'%>
  <%= form.submit 'GO', id:"dd"%>
  <% end %>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
<script type="text/javascript" >
  const wrapper = document.querySelector(".input-wrapper"),
  textInput = document.querySelector("input[type='text']");

  textInput.addEventListener("keyup", event => {
    wrapper.setAttribute("data-text", event.target.value);
  });

  var input = document.querySelector('input[type="text"]');

  input.addEventListener('keypress', function(e){
    if(e.which === 13){
      e.preventDefault();
      send_query();
    }
  });

 method_url= location.protocol + "//" + location.host +"/main/search.json"
      function send_query(){
      	  target = document.querySelector('#search');
          var param_str = "?" +
               "nick=" + target.value;
          if (param_str == "") return false;
           var my_JSON_object = {};
          var http_request = new XMLHttpRequest();
          http_request.open("GET", method_url+param_str, true);
          http_request.onreadystatechange = function () {
              var done = 4, ok = 200;
              if (http_request.readyState == done &&
                  http_request.status == ok) {
              	 my_JSON_object =
                      JSON.parse(http_request.responseText);
                  result(my_JSON_object.influencers);
              }
          };
          http_request.send(null);
          return false;
      }
 
      function result(influencers){
        target = document.querySelector('.all_card');
        html = "";
        if (influencers.length == 0) {
          html += "<div id=\"sorry\"> К сожалению, ни один инфлюенсер не найден </div>";
        } else {
          for (influencer of influencers) {
            html += "<a href=\"../../profile/" + influencer.id.toString() +"\"><div class=\" small_card card \">";
            html += "<img src= '"+influencer.avatar.toString()+"' class='avatar' width=\"270\" height=\"270\">";
            html += "<div class=\"nick\"><span >@" + influencer.nick.toUpperCase().toString() + "</span></div>";
            html += "<div class=\"nick\">" + influencer.name +" "+influencer.surname + "</div>";
            html +="</div></a>";
          }
        }

        target.innerHTML = "";
        target.innerHTML = html; 
        tar = document.querySelector('#link');
        tar.remove();
        a = document.querySelector('#dd');
        a.remove();
        document.querySelector('#platform_id').remove();
        document.querySelector('#tag_id').remove();
        document.querySelector('#all').style.display="block";
        document.querySelector('#all').style.marginLeft="400px";
      }
    
</script>
<div class="all_card">
  <% @influencers.each do |influencer| %>
  <a href="../../profile/<%= influencer.id %>">
    <div class="card">
      <img src= '<%= influencer.avatar %>' class='avatar' width="270" height="270">
      <div class="nick">
        <span ><%= influencer.nick.upcase %> </span>
      </div>
      <div>
        <% influencer.subscribers.each do |subscriber|%>
        <% if subscriber.main%>
        <img class='icon' src="../<%= subscriber.platform.icon%> " width="40" height="40">
        <span class="main_count"><%= subscriber.number_of_subscribers%> +</span>
        </br></br>
        <%else%>
        <img class='icon' src="../<%= subscriber.platform.icon%> " width="40" height="40">
        <span class="count"><%= subscriber.number_of_subscribers.to_i / 1000%> thou.</span>
        <%end%>
        <%end%>
      </div>
    </div>
  </a>
  <% end %>
</div>
<%= link_to  image_tag(image_path('стрелка.png'), class: "mini"), main_add_cards_path(), remote: true, id: "link" , title: 'Загрузить еще инфлюенсеров'%>
<div id="lil">
  <div id="lol"></div>
</div>